import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center gap-4 py-8">
        <h1 className="text-2xl">Home</h1>
        <div className="text-blue-400 underline cursor-pointer flex flex-col items-center gap-2">
          <Link href={'/users'}>Users page (Only for authenticated users)</Link>
          <Link href={'/login'}>
            Login page (Only for unauthenticated users)
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Home;
