import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { login, me } from '@/common/auth';
import { AxiosError } from 'axios';
import Router from 'next/router';

const Login: NextPage = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  const handleLogin = async () => {
    setError('');
    try {
      await login(email, password);
      Router.push('/users');
    } catch (error: any) {
      const axiosError = error as AxiosError;
      setError(axiosError.message);
    }
  };

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center gap-4 py-5">
        <h1 className="text-xl">Sign in using credentials:</h1>
        <div className="text-red-500">{error}</div>
        <input
          className="border rounded p-3"
          type="text"
          placeholder="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        <input
          className="border rounded p-3"
          type="password"
          placeholder="Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <button onClick={handleLogin}>Login</button>
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const redirect = {
    redirect: {
      destination: '/',
      permanent: false,
    },
  };

  try {
    const { data } = await me(req.headers.cookie);
    if (data.id) {
      return redirect;
    }
  } catch (error) {
    return { props: {} };
  }
  return { props: {} };
};

export default Login;
